/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Achievement Gotten!": "成就达成！",
    "clic on a booster to buy it": "点击一个助推器以购买",
    "Developement: Jean Joulia": "开发：Jean Joulia",
    "Do you want to reset the game?": "你想重置游戏吗？",
    "https://www.melissaledoux.fr": "https://www.melissaledoux.fr",
    "Illustration: Mélissa ledoux": "插图：Mélissa ledoux",
    "jean.joulia.france@gmail.com": "jean.joulia.france@gmail.com",
    "Reset": "重置",
    "<strong>Moist chameleon is an idle game about opening booster of cards and combining cards to make new\n            one</strong>": "<strong>潮湿的变色龙是一款关于打开卡片助推器，并将卡片组合成新的的一款放置类游戏</strong>",
    "Moist chameleon is an idle game about opening booster of cards and combining cards to make new\n            one": "潮湿的变色龙是一款关于打开卡片助推器并将卡片组合成新的休闲游戏\n",
    "A big crystal found deep in the earth core. You can use it as currency when trading with the mirage shopkeeper. Better have a few before shopping.": "在地核深处发现的一块大水晶。 与海市蜃楼掌柜交易时，您可以将其用作货币。 购物前最好有一些。",
    "Fortune cookie": "幸运饼干",
    "Normal": "普通",
    "Play": "出牌",
    "Rare": "稀有",
    "Rare coin": "稀有硬币",
    "This card will make the 5 next cards sell for 3 times their value. This coin is made of luckium, a very rare metal.": "这张卡将使接下来的 5 张卡以 3 倍的价格出售。 这枚硬币是由一种非常稀有的金属 Lucium 制成的。",
    "This cookie will give you info on how to get a specific card. The cookie itself is just sugar and butter but the paper inside was written by someone who knew what you were looking for.": "此 cookie 将为您提供有关如何获取特定卡的信息。 饼干本身只是糖和黄油，但里面的纸是由知道你在找什么的人写的。",
    "wallet is full": "钱包满了",
    "Fast worker": "快速工作者",
    "Upon playing, this card will double the speed at which you generate currency for 10 minutes. Playing it multiple times won't make it faster but will make it last longer.": "打出后，这张卡会使你产生货币的速度翻倍，持续 10 分钟。 多次打出不会使其更快，但会使其持续更长时间。",
    "Bubble are fragile and will disappear in a pop. The soap used is low PH and dairy free so it won't hurt your eyes. The soap do contain peanut traces. Carrying an epipen is strongly advised.": "泡沫是脆弱的，会突然消失。使用的肥皂是低 PH 值且不含乳制品，因此不会伤害您的眼睛。肥皂确实含有花生痕迹。强烈建议携带 Epipen。",
    "Bubbles": "气泡",
    "During the day, the king is lucky with dice. The next time you play the card [22:Risky dice] you can only roll positively. You better get away from him at night.": "白天，国王幸运骰子。下次你打出这张牌 [22:Risky dice] 时，你只能投正。你最好在晚上远离他。",
    "Dwarf worker": "矮人工人",
    "Generous magpie": "慷慨的喜鹊",
    "Greasy cauldron": "油腻的大锅",
    "King of dice": "骰子之王",
    "Old dungeon": "古老的地牢",
    "Soapy water": "肥皂水",
    "This big pot is all rusted and dirty. The card soapy water may help you clean it.": "这个大锅全都生锈了，脏兮兮的。卡片肥皂水可以帮助您清洁它。",
    "This card can only be played when there are 7 of them. Playing it will destroy the 7 cards. The normal version of the card will be destroyed before the rare one.": "这张卡只有7张才能打出。玩它会破坏7张牌。普通版的卡牌会在稀有版之前被销毁。",
    "This card will turn a random card in a booster into a rare version of itself. It will only work on a booster not yet opened.": "这张牌会将补充包中的一张随机牌变成它自己的稀有版本。它仅适用于尚未打开的助推器。",
    "This magpie will return with shiny objects if it can find one. This beautiful bird lives near an old woman's house. It is waiting on an occasion to steal her necklace.": "如果这只喜鹊能找到一个，它会带着闪亮的物体返回。这只美丽的鸟住在一位老妇人的房子附近。它正在伺机偷走她的项链。",
    "Upon playing, this card will double the speed at which you generate currency for 20 minutes. Playing it multiple times won't make it faster but will make it last longer.": "使用时，这张卡会使你产生货币的速度加倍，持续 20 分钟。多次播放不会使其更快，但会使其持续更长时间。",
    "While traveling in Europe, you find an old dungeon deep in the forest. Inside you find a skeleton leg chained to the wall.": "在欧洲旅行时，您会在森林深处发现一个古老的地牢。在里面你会发现一条被锁在墙上的骷髅腿。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "<strong>": "<strong>",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Emerald": "翡翠",
    "</strong>": "</strong>",
    "Fortune cookie": "幸运饼干",
    "Generous magpie": "慷慨的喜鹊",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^Normal: ([\d\.,]+) \- rare: ([\d\.,]+)$/, '普通: $1 \- 稀有: $2'],
    [/^Sell ([\d\.,]+)$/, '出售 $1'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);